services:
    - type: worker
      name: family-city-bot
      runtime: node
      buildCommand: npm install && npm run build
      startCommand: npm run start
      envVars:
        - key: NODE_ENV
          value: production
        - key: PORT
          value: 3000
        - key: DISCORD_BOT_TOKEN
          sync: false
        - key: DISCORD_GUILD_ID
          sync: false
        - key: DISCORD_LOG_CHANNEL_ID
          sync: false
        - key: DISCORD_ADMIN_ROLE_ID
          sync: false
  